:toc: macro

ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

toc::[]
:idprefix:
:idseparator: -
:reproducible:
:source-highlighter: rouge
:listing-caption: Listing

= devon4ng library

This project was generated with https://github.com/angular/angular-cli[Angular CLI] version 7.3.6 and upgraded to Angular 8.0.1. It contains the devon4ng libraries. 

== Library catalogue

This repository includes the following devon4ng libraries.

- link:projects\devon4ng\cache\README.md[Cache Module] for Angular 7+ projects.
- link:projects\devon4ng\authorization\README.md[Authorization Module] for Angular 7+ projects.

== Project Requirements

In order to use these libraries your project must use at least **Angular 7** in order to ensure the library will work as expected. 

== How to contribute

Please follow our link:.github/CONTRIBUTING_GUIDE.asciidoc[Contributing Guide], therefore the contributor must make a Pull Request with the new developed library following our https://github.com/devonfw/devon4ng/wiki/guide-angular-library#generating-a-library[Angular Library] documentation file:

[source, bash]
----
$ ng generate library @devon4ng/library-name --prefix library-prefix-wanted 
----

NOTE: Prefix is optional. 

After reviewing this PR the devonfw Core Team will publish the NPM package in case the library maintains the expected quality level.
